# Generated by Django 4.1 on 2024-02-14 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits.", regex="^\\d{10}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Pincode must be 6 digits.", regex="^\\d{6}$"
                    )
                ],
            ),
        ),
    ]
