# Generated by Django 4.1 on 2024-02-18 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(default="", max_length=200)),
                ("vehicle_name", models.CharField(default="", max_length=200)),
                ("location_from", models.CharField(default="", max_length=200)),
                ("location_to", models.CharField(default="", max_length=200)),
                ("available_on", models.DateField(default=django.utils.timezone.now)),
                ("departure_time", models.TimeField(default=django.utils.timezone.now)),
                ("price_ton", models.FloatField(default=0)),
                ("capacity", models.FloatField(default=0)),
                ("specifications", models.TextField()),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
