# Generated by Django 5.0.2 on 2024-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product_taluka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
