# Generated by Django 4.1 on 2024-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="confirm_password",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
