# Generated by Django 5.0.2 on 2024-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(default='', max_length=300, primary_key=True, serialize=False),
        ),
    ]
