# Generated by Django 4.1 on 2024-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_ridebooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridebooking",
            name="ride_complete",
            field=models.BooleanField(default=False),
        ),
    ]
