# Generated by Django 4.1 on 2024-02-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_ridebooking_ride_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booker_sign",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="lender_sign",
        ),
        migrations.RemoveField(
            model_name="ridebooking",
            name="ride_complete",
        ),
        migrations.AddField(
            model_name="ridebooking",
            name="ride_confirm",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
