# Generated by Django 5.0.2 on 2024-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_booking_number_of_hours_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='lender_sign',
            field=models.BooleanField(default=False),
        ),
    ]
