# Generated by Django 5.0.2 on 2024-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_booking_booker_sign_booking_lender_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='when_date',
            field=models.DateField(default='2024-02-02'),
        ),
    ]
