# Generated by Django 5.1.7 on 2025-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_booking_when_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
