# Generated by Django 5.1.7 on 2025-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
